
import json
import os
import subprocess
import sys

import typer
from rich.console import Console
from rich.table import Table as RichTable
from rich.panel import Panel

from mcp_maker import __version__
from mcp_maker.core.schema import DataSourceSchema
from mcp_maker.connectors.base import get_connector, register_connector
from mcp_maker.core.generator import generate_server_code, write_server
from .main import app, console



ENV_FILE = ".env"

# Known environment variables and their connectors
_KNOWN_VARS = {
    "AIRTABLE_API_KEY": "Airtable API key (Personal Access Token)",
    "AIRTABLE_TOKEN": "Airtable API key (alias)",
    "NOTION_API_KEY": "Notion integration secret",
    "NOTION_TOKEN": "Notion integration secret (alias)",
    "GOOGLE_SERVICE_ACCOUNT_FILE": "Path to Google service account JSON file",
    "GOOGLE_CREDENTIALS_JSON": "Google credentials JSON content (for deployment)",
}




def _env_read(env_file: str) -> dict[str, str]:
    """Read a .env file into a dict."""
    env_vars = {}
    if not os.path.isfile(env_file):
        return env_vars
    with open(env_file, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                k, _, v = line.partition("=")
                # Strip quotes
                v = v.strip().strip("'").strip('"')
                env_vars[k.strip()] = v
    return env_vars


def _env_write(env_file: str, env_vars: dict[str, str]):
    """Write a dict to a .env file."""
    with open(env_file, "w") as f:
        f.write("# MCP-Maker Environment Variables\n")
        f.write("# Generated by: mcp-maker env\n")
        f.write("# Load with: source .env or use with Claude Desktop config\n\n")
        for k, v in sorted(env_vars.items()):
            # Quote values with spaces
            if " " in v or "'" in v:
                f.write(f'{k}="{v}"\n')
            else:
                f.write(f"{k}={v}\n")


def _mask_value(value: str) -> str:
    """Mask a sensitive value for display."""
    if len(value) <= 8:
        return "****"
    return value[:6] + "..." + value[-4:]


def _env_set(env_file: str, key: str, value: str):
    """Set an environment variable."""
    env_vars = _env_read(env_file)
    is_new = key not in env_vars
    env_vars[key] = value
    _env_write(env_file, env_vars)

    action = "Set" if is_new else "Updated"
    console.print(f"\n  ✅ {action}: [cyan]{key}[/cyan] = [dim]{_mask_value(value)}[/dim]")
    console.print(f"  📁 Saved to: [green]{env_file}[/green]")

    if key in _KNOWN_VARS:
        console.print(f"  💡 {_KNOWN_VARS[key]}")

    console.print()
    console.print("  [dim]To use in your shell:[/dim]")
    console.print(f"    [cyan]source {env_file}[/cyan]")
    console.print()
    console.print("  [dim]To use in Claude Desktop config, add to env:[/dim]")
    console.print(f'    [cyan]"{key}": "{_mask_value(value)}"[/cyan]\n')


def _env_list(env_file: str):
    """List all environment variables."""
    env_vars = _env_read(env_file)

    if not env_vars:
        console.print(f"\n  No variables found in [dim]{env_file}[/dim]")
        console.print(f"\n  Set one with: [cyan]mcp-maker env set KEY VALUE[/cyan]")
        console.print()
        console.print("  [dim]Common variables:[/dim]")
        for k, desc in _KNOWN_VARS.items():
            console.print(f"    [cyan]{k}[/cyan] — {desc}")
        console.print()
        return

    table = RichTable(title=f"🔐 Environment Variables ({env_file})")
    table.add_column("Variable", style="cyan", no_wrap=True)
    table.add_column("Value (masked)", style="green")
    table.add_column("Description", style="dim")

    for k, v in sorted(env_vars.items()):
        desc = _KNOWN_VARS.get(k, "")
        table.add_row(k, _mask_value(v), desc)

    console.print()
    console.print(table)
    console.print()


def _env_show(env_file: str, key: str):
    """Show the actual value of a variable."""
    env_vars = _env_read(env_file)
    if key not in env_vars:
        console.print(f"\n  [red]Not found:[/red] {key} is not set in {env_file}\n")
        raise typer.Exit(code=1)
    console.print(f"\n  [cyan]{key}[/cyan] = {env_vars[key]}\n")


def _env_delete(env_file: str, key: str):
    """Delete an environment variable."""
    env_vars = _env_read(env_file)
    if key not in env_vars:
        console.print(f"\n  [red]Not found:[/red] {key} is not set in {env_file}\n")
        raise typer.Exit(code=1)
    del env_vars[key]
    _env_write(env_file, env_vars)
    console.print(f"\n  ✅ Deleted: [cyan]{key}[/cyan] from {env_file}\n")

@app.command()
def env(
    action: str = typer.Argument(
        ...,
        help="Action: set, list, show, delete",
    ),
    key: str = typer.Argument(
        None,
        help="Environment variable name (e.g., AIRTABLE_API_KEY)",
    ),
    value: str = typer.Argument(
        None,
        help="Value to set (only for 'set' action)",
    ),
    env_file: str = typer.Option(
        ENV_FILE,
        "--file",
        help="Path to the .env file.",
    ),
):
    """🔐 Manage environment variables for API keys.

    Safely store API keys in a .env file instead of hardcoding them.

    Actions:
        set     Set a variable:    mcp-maker env set AIRTABLE_API_KEY pat_xxxx
        list    List all vars:     mcp-maker env list
        show    Show a var value:  mcp-maker env show AIRTABLE_API_KEY
        delete  Remove a var:      mcp-maker env delete AIRTABLE_API_KEY

    Examples:
        mcp-maker env set AIRTABLE_API_KEY pat_xxxxxxxxxxxx
        mcp-maker env set NOTION_API_KEY ntn_xxxxxxxxxxxx
        mcp-maker env set GOOGLE_SERVICE_ACCOUNT_FILE ./credentials.json
        mcp-maker env list
    """
    console.print()
    console.print(
        Panel.fit("🔐 [bold cyan]Environment Manager[/bold cyan]", subtitle="v" + __version__)
    )

    if action == "list":
        _env_list(env_file)
    elif action == "set":
        if not key or value is None:
            console.print("\n[red]Usage:[/red] mcp-maker env set KEY VALUE")
            console.print("  Example: mcp-maker env set AIRTABLE_API_KEY pat_xxxx\n")
            raise typer.Exit(code=1)
        _env_set(env_file, key, value)
    elif action == "show":
        if not key:
            console.print("\n[red]Usage:[/red] mcp-maker env show KEY")
            raise typer.Exit(code=1)
        _env_show(env_file, key)
    elif action == "delete":
        if not key:
            console.print("\n[red]Usage:[/red] mcp-maker env delete KEY")
            raise typer.Exit(code=1)
        _env_delete(env_file, key)
    else:
        console.print(f"\n[red]Unknown action:[/red] {action}")
        console.print("  Valid actions: set, list, show, delete\n")
        raise typer.Exit(code=1)
