"""
Auto-generated MCP Server tools by MCP-Maker
Source: sqlite

⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
This file is overwritten every time you run `mcp-maker init`.
Add your custom tools to `mcp_server.py` instead.
"""

import traceback
import os
import sys

# Load connection string from environment to prevent credential exposure in source code
DATABASE_URL = os.environ.get("DATABASE_URL")


import sqlite3
import threading


from mcp.server.fastmcp import FastMCP

# ─── Server Setup ───

mcp = FastMCP("sqlite-server")


# ─── Database Connection (Thread-Safe) ───

DB_PATH = DATABASE_URL
if DB_PATH and DB_PATH.startswith("sqlite:///"):
    DB_PATH = DB_PATH[len("sqlite:///"):]
elif DB_PATH and DB_PATH.startswith("sqlite://"):
    DB_PATH = DB_PATH[len("sqlite://"):]
if not DB_PATH:
    DB_PATH = "/var/folders/k2/1ydmv0l505z3dbt_hl9fqc3m0000gp/T/tmpmf7ist8c.db"

_local = threading.local()


def _get_connection():
    """Get a thread-local SQLite connection (reused across calls)."""
    if not hasattr(_local, "conn") or _local.conn is None:
        conn = sqlite3.connect(DB_PATH, check_same_thread=False)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA journal_mode=WAL")  # Better concurrent read performance
        _local.conn = conn
    return _local.conn

# ─── Consolidated Tools (Large Schema Mode) ───

@mcp.tool()
def list_tables() -> list[str]:
    """List all available tables in the database."""
    conn = _get_connection()
    try:
        cursor = conn.execute("SELECT name FROM sqlite_master WHERE type='table'")
        return [row["name"] for row in cursor.fetchall()]
    except Exception as e:
        raise RuntimeError(f"list_tables failed: {e}") from e

@mcp.tool()
def describe_table(table_name: str) -> dict:
    """Get the schema (columns and types) for a specific table."""
    conn = _get_connection()
    try:
        cursor = conn.execute(f'PRAGMA table_info("{table_name}")')
        return {row["name"]: row["type"] for row in cursor.fetchall()}
    except Exception as e:
        raise RuntimeError(f"describe_table failed: {e}") from e

@mcp.tool()
def query_database(table_name: str, filters: dict | None = None, limit: int = 50, offset: int = 0) -> list[dict]:
    """Query a table with optional exact-match filters (e.g. {"status": "active"})."""
    conn = _get_connection()
    try:
        limit = min(limit, 500)
        query = f'SELECT * FROM "{table_name}"'
        params = []
        if filters:
            conditions = []
            for k, v in filters.items():
                conditions.append(f'"{k}" = ?')
                params.append(v)
            query += " WHERE " + " AND ".join(conditions)
        query += " LIMIT ? OFFSET ?"
        params.extend([limit, offset])
        cursor = conn.execute(query, params)
        return [dict(row) for row in cursor.fetchall()]
    except Exception as e:
        raise RuntimeError(f"query_database failed: {e}") from e





