"""
Auto-generated MCP Server tools by MCP-Maker
Source: sqlite

⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
This file is overwritten every time you run `mcp-maker init`.
Add your custom tools to `mcp_server.py` instead.
"""

import os

# Load connection string from environment to prevent credential exposure in source code
DATABASE_URL = os.environ.get("DATABASE_URL")


import sqlite3
import threading


from mcp.server.fastmcp import FastMCP

# ─── Server Setup ───

mcp = FastMCP("sqlite-server")






# ─── Database Connection (Thread-Safe) ───

DB_PATH = DATABASE_URL
if DB_PATH and DB_PATH.startswith("sqlite:///"):
    DB_PATH = DB_PATH[len("sqlite:///"):]
elif DB_PATH and DB_PATH.startswith("sqlite://"):
    DB_PATH = DB_PATH[len("sqlite://"):]
if not DB_PATH:
    import warnings
    DB_PATH = "/var/folders/k2/1ydmv0l505z3dbt_hl9fqc3m0000gp/T/tmpost9xi_c.db"
    warnings.warn(
        f"DATABASE_URL not set. Using hardcoded path: {DB_PATH}. "
        "Set DATABASE_URL environment variable for production use.",
        stacklevel=1,
    )

_local = threading.local()


def _get_connection():
    """Get a thread-local SQLite connection (reused across calls)."""
    if not hasattr(_local, "conn") or _local.conn is None:
        conn = sqlite3.connect(DB_PATH, check_same_thread=False)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA journal_mode=WAL")  # Better concurrent read performance
        _local.conn = conn
    return _local.conn

# ─── Consolidated Tools (Large Schema Mode) ───

# Known tables discovered at generation time — prevents SQL injection
_KNOWN_TABLES = { "table_0", "table_1", "table_10", "table_11", "table_12", "table_13", "table_14", "table_15", "table_16", "table_17", "table_18", "table_19", "table_2", "table_20", "table_21", "table_22", "table_23", "table_24", "table_3", "table_4", "table_5", "table_6", "table_7", "table_8", "table_9",  }

def _validate_table(name: str) -> str:
    """Validate that a table name is in the known set to prevent SQL injection."""
    if name not in _KNOWN_TABLES:
        raise ValueError(f"Unknown table: {name}. Available: {', '.join(sorted(_KNOWN_TABLES))}")
    return name


@mcp.tool()
def list_tables() -> list[str]:
    """List all available tables in the database."""
    return sorted(_KNOWN_TABLES)


@mcp.tool()
def describe_table(table_name: str) -> dict:
    """Get the schema (columns and types) for a specific table."""
    table_name = _validate_table(table_name)
    conn = _get_connection()
    try:
        cursor = conn.execute(f'PRAGMA table_info("{table_name}")')
        return {row["name"]: row["type"] for row in cursor.fetchall()}
    except Exception as e:
        raise RuntimeError(f"describe_table failed: {e}") from e

@mcp.tool()
def query_database(table_name: str, filters: dict | None = None, limit: int = 50, offset: int = 0) -> list[dict]:
    """Query a table with optional filters.
    
    Supports exact match: {"status": "active"}
    Supports operators via suffixes:
      - __gt: Greater than ({"age__gt": 18})
      - __lt: Less than ({"price__lt": 100})
      - __like: LIKE match ({"name__like": "%John%"})
      - __in: IN array ({"id__in": [1, 2, 3]})
    """
    table_name = _validate_table(table_name)
    conn = _get_connection()
    try:
        limit = min(limit, 500)
        query = f'SELECT * FROM "{table_name}"'
        params = []
        if filters:
            conditions = []
            for k, v in filters.items():
                if k.endswith("__gt"):
                    conditions.append(f'"{k[:-4]}" > ?')
                elif k.endswith("__lt"):
                    conditions.append(f'"{k[:-4]}" < ?')
                elif k.endswith("__like"):
                    conditions.append(f'"{k[:-6]}" LIKE ?')
                elif k.endswith("__in") and isinstance(v, list):
                    placeholders = ", ".join(["?"] * len(v))
                    conditions.append(f'"{k[:-4]}" IN ({placeholders})')
                    params.extend(v)
                    continue
                else:
                    conditions.append(f'"{k}" = ?')
                params.append(v)
            query += " WHERE " + " AND ".join(conditions)
        query += " LIMIT ? OFFSET ?"
        params.extend([limit, offset])
        cursor = conn.execute(query, params)
        return [dict(row) for row in cursor.fetchall()]
    except Exception as e:
        raise RuntimeError(f"query_database failed: {e}") from e







# ─── Health Check ───

@mcp.tool()
def server_health() -> dict:
    """Check the health status of this MCP server.

    Returns:
        Server status including source type, table count, and uptime info.
    """
    return {
        "status": "healthy",
        "source_type": "sqlite",
        "tables": 25,
        "version": "mcp-maker",
    }

# ─── Graceful Shutdown ───

import atexit

def _cleanup():
    """Clean up database connections on server shutdown."""
    if hasattr(_local, "conn") and _local.conn:
        try:
            _local.conn.close()
        except Exception:
            pass

atexit.register(_cleanup)
# ─── Export Tools ───

import csv as _csv
import io as _io
import json as _json

@mcp.tool()
def export_table_0_csv(limit: int = 1000) -> str:
    """Export 'table_0' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_0(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_0_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_0' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_0(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_1_csv(limit: int = 1000) -> str:
    """Export 'table_1' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_1(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_1_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_1' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_1(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_10_csv(limit: int = 1000) -> str:
    """Export 'table_10' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_10(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_10_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_10' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_10(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_11_csv(limit: int = 1000) -> str:
    """Export 'table_11' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_11(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_11_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_11' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_11(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_12_csv(limit: int = 1000) -> str:
    """Export 'table_12' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_12(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_12_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_12' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_12(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_13_csv(limit: int = 1000) -> str:
    """Export 'table_13' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_13(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_13_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_13' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_13(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_14_csv(limit: int = 1000) -> str:
    """Export 'table_14' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_14(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_14_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_14' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_14(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_15_csv(limit: int = 1000) -> str:
    """Export 'table_15' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_15(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_15_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_15' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_15(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_16_csv(limit: int = 1000) -> str:
    """Export 'table_16' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_16(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_16_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_16' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_16(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_17_csv(limit: int = 1000) -> str:
    """Export 'table_17' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_17(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_17_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_17' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_17(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_18_csv(limit: int = 1000) -> str:
    """Export 'table_18' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_18(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_18_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_18' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_18(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_19_csv(limit: int = 1000) -> str:
    """Export 'table_19' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_19(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_19_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_19' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_19(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_2_csv(limit: int = 1000) -> str:
    """Export 'table_2' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_2(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_2_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_2' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_2(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_20_csv(limit: int = 1000) -> str:
    """Export 'table_20' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_20(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_20_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_20' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_20(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_21_csv(limit: int = 1000) -> str:
    """Export 'table_21' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_21(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_21_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_21' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_21(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_22_csv(limit: int = 1000) -> str:
    """Export 'table_22' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_22(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_22_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_22' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_22(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_23_csv(limit: int = 1000) -> str:
    """Export 'table_23' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_23(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_23_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_23' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_23(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_24_csv(limit: int = 1000) -> str:
    """Export 'table_24' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_24(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_24_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_24' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_24(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_3_csv(limit: int = 1000) -> str:
    """Export 'table_3' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_3(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_3_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_3' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_3(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_4_csv(limit: int = 1000) -> str:
    """Export 'table_4' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_4(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_4_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_4' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_4(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_5_csv(limit: int = 1000) -> str:
    """Export 'table_5' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_5(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_5_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_5' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_5(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_6_csv(limit: int = 1000) -> str:
    """Export 'table_6' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_6(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_6_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_6' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_6(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_7_csv(limit: int = 1000) -> str:
    """Export 'table_7' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_7(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_7_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_7' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_7(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_8_csv(limit: int = 1000) -> str:
    """Export 'table_8' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_8(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_8_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_8' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_8(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)

@mcp.tool()
def export_table_9_csv(limit: int = 1000) -> str:
    """Export 'table_9' data as CSV string.

    Args:
        limit: Maximum rows to export (default: 1000).
    """
    result = list_table_9(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    if not rows:
        return ""
    output = _io.StringIO()
    writer = _csv.DictWriter(output, fieldnames=rows[0].keys())
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()

@mcp.tool()
def export_table_9_json(limit: int = 1000, indent: int = 2) -> str:
    """Export 'table_9' data as formatted JSON string.

    Args:
        limit: Maximum rows to export (default: 1000).
        indent: JSON indentation (0 for compact).
    """
    result = list_table_9(limit=limit)
    rows = result["results"] if isinstance(result, dict) else result
    return _json.dumps(rows, indent=indent if indent > 0 else None, default=str)


